language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t m4r14r1os/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true m4r14r1os/complex-test npm test

after_success:
  - docker build -t m4r14r1os/complex-multi-client ./client
  - docker build -t m4r14r1os/complex-multi-nginx ./nginx
  - docker build -t m4r14r1os/complex-multi-server ./server
  - docker build -t m4r14r1os/complex-multi-worker ./worker