language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t m4r14r1os/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true m4r14r1os/complex-test npm test

after_success:
  - docker build -t m4r14r1os/complex-multi-client ./client
  - docker build -t m4r14r1os/complex-multi-nginx ./nginx
  - docker build -t m4r14r1os/complex-multi-server ./server
  - docker build -t m4r14r1os/complex-multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push m4r14r1os/complex-multi-client
  - docker push m4r14r1os/complex-multi-nginx
  - docker push m4r14r1os/complex-multi-server
  - docker push m4r14r1os/complex-multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-289913794490"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
