apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auntie-mariamaldonado-com-tls
spec:
  secretName: auntie-mariamaldonado-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auntie-mariamaldonado.com
  dnsNames:
    - auntie-mariamaldonado.com
    - www.auntie-mariamaldonado.com